platform :ios, '11.0'
use_frameworks!

target 'SoulSwift_Example' do
  pod 'SoulSwift', :path => '../'

  target 'SoulSwift_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
