use_frameworks!

target 'SoulSwift_Example' do
  pod 'SoulSwift', :path => '../'

  target 'SoulSwift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
