default_platform(:ios)

platform :ios do
  
  lane :lint do
    swiftlint
  end

  lane :tests do
    run_tests(workspace: "SoulSwift.xcworkspace",
              scheme: "SoulSwift-Example")
  end
end
