default_platform(:ios)

platform :ios do
  
  lane :lint do
    swiftlint
  end

  lane :tests do
    run_tests(workspace: "SoulSwift.xcworkspace",
              formatter: "xcpretty-json-formatter",
              output_types: "html,junit",
              scheme: "SoulSwift-Example")
    # slather(teamcity: true)
  end

end
