default_platform(:ios)

platform :ios do

  lane :lint do
    swiftlint(reporter: "html",
              output_file: "fastlane/swiftlint_output/swiftlint.html")
  end

  lane :tests do
    cocoapods
    run_tests(workspace: "SoulSwift.xcworkspace",
              scheme: "SoulSwift-Example",
              formatter: "xcpretty-json-formatter",
              output_types: "html,junit",
              output_directory: "fastlane/tests_output")
  end

  lane :coverage do
    xcov(workspace: "SoulSwift.xcworkspace",
         scheme: "SoulSwift-Example",
         include_targets: "SoulSwift.framework",
         output_directory: "fastlane/xcov_output")
  end
end
